### ISSUE TITLE
Running nmap as root or fakeroot

### ISSUE THREAD

**Issue by FilipStyno** [AdarshAddee/root#13]
Whenever I try to run nmap with root privileges "nmap -sS kali.org" or casual "nmap kali.org" it shows this error: route_dst_netlink: can't find interface "wlan0". But I can run "nmap kali.org" without root privileges without any problem. Thanks for answers.

**Comment by AdarshAddee** [comment]
you have to install nethunter for root access. You can use root privileges for nmap.
