### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by Wulfwunda** [AdarshAddee/root#18]
This git changed the termux style, how can i set it back?

**Comment by belongtothenight** [comment]
You can use "exit" to leave the environment. If you don't like it, you can use "apt remove fish" to get rid of it.
But anyways, this repo doesn't work on my Android 13 phone. ＞﹏＜

**Comment by AdarshAddee** [comment]
Well you use uninstall.sh to get back your previous look. Thank you for using this tool.
