### ISSUE TITLE
Can't get sudo access?

### ISSUE THREAD

**Issue by agcrisbp** [AdarshAddee/root#19]
![Screenshot_2023-04-15-18-09-55-057_com termux](https://user-images.githubusercontent.com/54905291/232210405-37b89fda-6a6e-4570-8551-aec46c6c94b8.png)

**Comment by TrollSkull** [comment]
because its just a pseudo-root wich fakes the root privileges.

**Comment by AdarshAddee** [comment]
As I mentioned in the very first line this tool will not give you real root permission.
