### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by K4rPinch0** [adarshaddee/root#2]
How i have exit of mode root?

**Comment by SX-9** [comment]
I have the same question

**Comment by SX-9** [comment]
Make sure to backup bash.bashrc tho

**Comment by adarshaddee** [comment]
hey sorry for inconvenience. You can exit from root mode by just entering command `exit`. Hope this will help you and resolve your issue. If you still have any issues you can ask me anytime.

Thank you for using out tool!

Have a nice day!

**Comment by kurunari5** [comment]
Bro can give me a whatsapp number banning tool

**Comment by adarshaddee** [comment]
Sorry, But I can't!
