### ISSUE TITLE
Terrible - Trash Script

### ISSUE THREAD

**Issue by x5bgray** [AdarshAddee/root#26]
People really have no shame these days. The script is trash. It just installs some packages and alias's proot.... Aka pseudo-root

**Comment by HaCkEr75321** [comment]
No it is a good tool maybe it dosen't give full root access but at least it gives some features in the root access which makes some tools work (i rate it 7/10)

**Comment by TrollSkull** [comment]
> No it is a good tool maybe it dosen't give full root access but at least it gives some features in the root access which makes some tools work (i rate it 7/10)

"`proot -0 login`". The option -0 just fake the root privileges, wich makes the user just appear like is using root, check the proot package :)

**Comment by AdarshAddee** [comment]
as I mentioned in the very first line that this tool will never give you real root access.
