### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by crinccc** [AdarshAddee/root#5]
I tried to do a command that needed root privilege,  but it threw 'permission denied' error and _WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"_

**Comment by AdarshAddee** [comment]
Well I have clearly mentioned that it does not provide you root access at top level. It can provide you root access just for small issues. You have to install linux distro at cli version to get root access for that level. 

Try https://github.com/AdarshAddee/linux-distro and you can visit https://youtube.com/mridealhat for more
