### ISSUE TITLE
Add uninstall info 

### ISSUE THREAD

**Issue by maxfpvaustria** [AdarshAddee/root#9]
Can you please add a guide how to uninstall this

**Comment by kosuke14** [comment]
just run this (do not run this code if you have already uninstalled it)
```
rm /data/data/com.termux/files/usr/etc/bash.bashrc
mv /data/data/com.termux/files/usr/etc/bash.bashrc_old /data/data/com.termux/files/usr/etc/bash.bashrc
```

**Comment by AdarshAddee** [comment]
Successfully added uninstall file. you can execute that file and uninstall this from your device.
